[project]
name = "tg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.45",
    "telebot>=0.0.5",
]
